In [12]:
import numpy as np

In [15]:
#array declaration
arr=np.array([1,2,3,4,5,3,2,12])
print(arr)

[ 1  2  3  4  5  3  2 12]


In [18]:
b=np.array([[1,2,3,4],[3,4,5,6]])
print(b)

[[1 2 3 4]
 [3 4 5 6]]


In [20]:
# zeros method
c=np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [23]:
# ones() method
d=np.ones((2,2))
print(d)


[[1. 1.]
 [1. 1.]]


In [26]:
#add two arrays
arr=np.array([[1,2,3,4],[5,3,2,12]])
b=np.array([[1,2,3,4],[3,4,5,6]])
s=arr+b
print(s)


[[ 2  4  6  8]
 [ 8  7  7 18]]


In [28]:
#multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[1,2],[3,4]])
f=d+e
print(f)

[[2 4]
 [6 8]]


In [32]:
#perform Matrix multiplication
a1=np.array([[1,2],[5,3,]])
b1=np.array([[5,4],[11,33]])
x=np.dot(a1,b1)
print(x)

[[ 27  70]
 [ 58 119]]
